version: "2"

services:
  reverse_proxy:
    build:
      dockerfile: Dockerfile-dev
    ports:
      - "80:80"

  web_1:
    build:
      dockerfile: Dockerfile-dev
    volumes:
      - ./web/src:/app/src
    expose:
      - "${WEB_PORT}"
    command:
      [
        "/wait-for-it.sh",
        "database:${DATABASE_PORT}",
        "--",
        "nodemon",
        "-L",
        "src/server.js",
      ]

  web_2:
    build:
      dockerfile: Dockerfile-dev
    volumes:
      - ./web/src:/app/src
    expose:
      - "${WEB_PORT}"
    command:
      [
        "/wait-for-it.sh",
        "database:${DATABASE_PORT}",
        "--",
        "nodemon",
        "-L",
        "src/server.js",
      ]

  worker:
    build:
      dockerfile: Dockerfile-dev
    volumes:
      - ./worker/src:/app/src
    command:
      [
        "/wait-for-it.sh",
        "database:${DATABASE_PORT}",
        "--",
        "nodemon",
        "-L",
        "src/app.js",
      ]

  database:
    expose:
      - "${DATABASE_PORT}"

  cache:
    expose:
      - "${CACHE_PORT}"
