version: "2"

services:
  reverse_proxy:
    build:
      dockerfile: Dockerfile-prod

  web_1:
    build:
      dockerfile: Dockerfile-prod
    command:
      [
        "/wait-for-it.sh",
        "database:${POSTGRES_PORT}",
        "--",
        "node",
        "src/server.js",
      ]

  web_2:
    build:
      dockerfile: Dockerfile-prod
    command:
      [
        "/wait-for-it.sh",
        "database:${POSTGRES_PORT}",
        "--",
        "node",
        "src/server.js",
      ]

  worker:
    build:
      dockerfile: Dockerfile-prod
    command:
      [
        "/wait-for-it.sh",
        "database:${POSTGRES_PORT}",
        "--",
        "node",
        "src/app.js",
      ]
