version: "2"

services:
  reverse_proxy:
    build:
      context: ./reverse-proxy
    image: networkapi/nginx
    networks:
      - webnet
    depends_on:
      - web_1
      - web_2
    restart: unless-stopped

  web_1:
    build:
      context: ./web
    image: networkapi/node_web
    env_file:
      - ./.env
    networks:
      - dbnet
      - webnet
    depends_on:
      - database
    restart: unless-stopped

  web_2:
    build:
      context: ./web
    image: networkapi/node_web
    env_file:
      - ./.env
    networks:
      - dbnet
      - webnet
    depends_on:
      - database
    restart: unless-stopped

  worker:
    build:
      context: ./worker
    image: networkapi/node_worker
    env_file:
      - ./.env
    networks:
      - dbnet
      - webnet
    depends_on:
      - database
    restart: unless-stopped

  database:
    build: ./database
    image: networkapi/postgres
    env_file:
      - ./.env
    volumes:
      - networkapi_database:/var/lib/postgresql/data
    networks:
      - dbnet
    restart: unless-stopped

  cache:
    image: redis
    networks:
      - dbnet
    restart: unless-stopped

volumes:
  networkapi_database:
    external: true

networks:
  dbnet:
    driver: bridge
  webnet:
    driver: bridge