version: "2"

services:
  reverse_proxy:
    build:
      dockerfile: Dockerfile-prod

  web_1:
    build:
      dockerfile: Dockerfile-prod
    volumes:
      - ./web/log:/home/node/app/log
    expose:
      - "${WEB_PORT}"
    command:
      [
        "/wait-for-it.sh",
        "database:${DATABASE_PORT}",
        "--",
        "node",
        "src/server.js",
      ]

  web_2:
    build:
      dockerfile: Dockerfile-prod
    volumes:
      - ./web/log:/home/node/app/log
    expose:
      - "${WEB_PORT}"
    command:
      [
        "/wait-for-it.sh",
        "database:${DATABASE_PORT}",
        "--",
        "node",
        "src/server.js",
      ]

  worker:
    build:
      dockerfile: Dockerfile-prod
    volumes:
      - ./worker/log:/home/node/app/log
    command:
      [
        "/wait-for-it.sh",
        "database:${DATABASE_PORT}",
        "--",
        "node",
        "src/app.js",
      ]

  database:
    expose:
      - "${DATABASE_PORT}"

  cache:
    expose:
      - "${CACHE_PORT}"
