version: "2.2"

services:
  reverse_proxy:
    build:
      dockerfile: Dockerfile-prod

  web_1:
    build:
      dockerfile: Dockerfile-prod

  web_2:
    build:
      dockerfile: Dockerfile-prod

  worker:
    build:
      dockerfile: Dockerfile-prod
