version: "2.2"

services:
  reverse_proxy:
    build:
      dockerfile: Dockerfile-prod
    ports:
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  web_1:
    build:
      dockerfile: Dockerfile-prod

  web_2:
    build:
      dockerfile: Dockerfile-prod

  worker:
    build:
      dockerfile: Dockerfile-prod

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
