FROM node:9-alpine

# Add wait-for-it.sh to control startup timing
RUN apk add --no-cache bash
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

WORKDIR /app

# Install nodemon for hot reload
RUN npm install -g nodemon

# Install node modules, use a mounted volume for other src files when developing
COPY ./package* ./
RUN npm install