FROM node:9-alpine

# Add wait-for-it.sh to control startup timing
RUN apk add --no-cache bash
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Node image provides a non root user
USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# Copy only npm install files first to take advantage of cached Docker layers
COPY ./package* ./
RUN npm install --only=production

# Bundle app source
COPY . .

ENV NODE_EV production